### ISSUE TITLE
UI updates to fit more services

### ISSUE THREAD

**Issue by chasefleming** [onflow/fcl-discovery#81]
There are now a lot services that are listed in Discovery and more are coming. There is currently a scroll for the iFrame/rpc, but we need a more versatile and better looking solution across other methods like pop/rpc and tab/rpc for when a large number of services are listed. We need a UI update to address this.

This also needs to address the issue of layout for when a service may have multiple sub-services (e.g. WalletConnect has different pairings for each wallet).

**Comment by cybercent** [comment]
![Example](https://user-images.githubusercontent.com/195806/203836682-b96ff7d9-0711-4293-9b94-a34ade02f268.jpg)

We did a mockup for inspiration, to reduce the header size and leave more space for the wallet list.

**Comment by chasefleming** [comment]
@cybercent this looks great. There might be a larger redesign down the road -- but not sure when that will be -- so this looks like a nice way to solve the problem in the mean time using a lot of the elements we already have. I like it.

**Comment by chasefleming** [comment]
@cybercent I might not be able to get to this for a few weeks. Any chance your team wants to take it on?

**Comment by chasefleming** [comment]
@cybercent what icon set and font is this?
